theme: jekyll-theme-minimal
kramdown:
  toc_levels: 1..2
  parse_block_html: true
logo: assets/img/comred-movies-dots.png
description: "ReDial (Recommendation Dialogues) is an annotated dataset of dialogues, where users recommend movies to each other. The dataset was collected by a team of researchers working at <a href=\"https://polymtl.ca\">Polytechnique Montréal</a>, <a href=\"https://mila.quebec\">Montréal Institute of Learning Algorithms</a>, <a href=\"https://www.microsoft.com/en-us/research/lab/microsoft-research-montreal/\">Microsoft Research Montréal</a> and <a href=\"https://elementai.com\">Element AI</a>."
title: ReDial Dataset
dsname: ReDial
ds_n_dlgs: 11351
ds_n_dlgs_train: 10009
ds_n_dlgs_test: 1342
ds_license: CC BY 4.0 License
ds_license_link: http://creativecommons.org/licenses/by/4.0
